# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NetworkLibByRx' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NetworkLibByRx
  pod 'RxSwift'
 pod 'RxCocoa'
 pod 'Moya-ObjectMapper/RxSwift'
 pod 'RxOptional'
 pod 'RxAlamofire'

end
